"preserve_hierarchy": true
"files": [
  {
    "source": "/ArchiSteamFarm/Localization/Strings.resx",
    "translation": "/ArchiSteamFarm/Localization/Strings.%locale%.resx",
    "translation_replace": {
      ".lol-US.resx": ".qps-Ploc.resx",
      ".sr-CS.resx": ".sr-Latn.resx"
    }
  },
  {
    "source": "/ArchiSteamFarm.OfficialPlugins.SteamTokenDumper/Localization/Strings.resx",
    "translation": "/ArchiSteamFarm.OfficialPlugins.SteamTokenDumper/Localization/Strings.%locale%.resx",
    "translation_replace": {
      ".lol-US.resx": ".qps-Ploc.resx",
      ".sr-CS.resx": ".sr-Latn.resx"
    }
  },
  {
    "source": "/wiki/*.md",
    "translation": "/wiki/locale/%locale%/%file_name%-%locale%.%file_extension%",
    "ignore": [ "/**/_*.md" ]
  },
  {
    "source": "/wiki/_Sidebar.md",
    "translation": "/wiki/locale/%locale%/_Sidebar.md"
  }
]
