//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiSteamFarm.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiSteamFarm.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting trade: {0}.
        /// </summary>
        internal static string AcceptingTrade {
            get {
                return ResourceManager.GetString("AcceptingTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASF will automatically check for new versions every {0} hours..
        /// </summary>
        internal static string AutoUpdateCheckInfo {
            get {
                return ResourceManager.GetString("AutoUpdateCheckInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content:
        ///{0}.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured {0} property is invalid: {1}.
        /// </summary>
        internal static string ErrorConfigPropertyInvalid {
            get {
                return ResourceManager.GetString("ErrorConfigPropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASF V{0} has run into fatal exception before core logging module was even able to initialize!.
        /// </summary>
        internal static string ErrorEarlyFatalExceptionInfo {
            get {
                return ResourceManager.GetString("ErrorEarlyFatalExceptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}() {1}
        ///StackTrace:
        ///{2}.
        /// </summary>
        internal static string ErrorEarlyFatalExceptionPrint {
            get {
                return ResourceManager.GetString("ErrorEarlyFatalExceptionPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting with non-zero error code!.
        /// </summary>
        internal static string ErrorExitingWithNonZeroErrorCode {
            get {
                return ResourceManager.GetString("ErrorExitingWithNonZeroErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failing: {0}.
        /// </summary>
        internal static string ErrorFailingRequest {
            get {
                return ResourceManager.GetString("ErrorFailingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global config could not be loaded, please make sure that {0} exists and is valid! Follow setting up guide on the wiki if you&apos;re confused..
        /// </summary>
        internal static string ErrorGlobalConfigNotLoaded {
            get {
                return ResourceManager.GetString("ErrorGlobalConfigNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global config file has been removed!.
        /// </summary>
        internal static string ErrorGlobalConfigRemoved {
            get {
                return ResourceManager.GetString("ErrorGlobalConfigRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global database could not be loaded, if issue persists, please remove {0} in order to recreate database!.
        /// </summary>
        internal static string ErrorGlobalDatabaseNotLoaded {
            get {
                return ResourceManager.GetString("ErrorGlobalDatabaseNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid!.
        /// </summary>
        internal static string ErrorIsInvalid {
            get {
                return ResourceManager.GetString("ErrorIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusing to execute this function due to invalid DeviceID in ASF 2FA!.
        /// </summary>
        internal static string ErrorMobileAuthenticatorInvalidDeviceID {
            get {
                return ResourceManager.GetString("ErrorMobileAuthenticatorInvalidDeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bots are defined, did you forget to configure your ASF?.
        /// </summary>
        internal static string ErrorNoBotsDefined {
            get {
                return ResourceManager.GetString("ErrorNoBotsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null!.
        /// </summary>
        internal static string ErrorObjectIsNull {
            get {
                return ResourceManager.GetString("ErrorObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing {0} failed!.
        /// </summary>
        internal static string ErrorParsingObject {
            get {
                return ResourceManager.GetString("ErrorParsingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove old ASF binary, please remove {0} manually in order for update function to work!.
        /// </summary>
        internal static string ErrorRemovingOldBinary {
            get {
                return ResourceManager.GetString("ErrorRemovingOldBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed despite of {0} tries!.
        /// </summary>
        internal static string ErrorRequestFailedTooManyTimes {
            get {
                return ResourceManager.GetString("ErrorRequestFailedTooManyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check latest version!.
        /// </summary>
        internal static string ErrorUpdateCheckFailed {
            get {
                return ResourceManager.GetString("ErrorUpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not proceed with update because there is no asset that relates to currently running binary! Please ensure that your ASF binary is named appropriately!.
        /// </summary>
        internal static string ErrorUpdateNoAssetForThisBinary {
            get {
                return ResourceManager.GetString("ErrorUpdateNoAssetForThisBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not proceed with an update because that version doesn&apos;t include any assets!.
        /// </summary>
        internal static string ErrorUpdateNoAssets {
            get {
                return ResourceManager.GetString("ErrorUpdateNoAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a request for user input, but process is running in headless mode!.
        /// </summary>
        internal static string ErrorUserInputRunningInHeadlessMode {
            get {
                return ResourceManager.GetString("ErrorUserInputRunningInHeadlessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusing to handle the request because SteamOwnerID is not set!.
        /// </summary>
        internal static string ErrorWCFAccessDenied {
            get {
                return ResourceManager.GetString("ErrorWCFAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF service could not be started because of AddressAccessDeniedException! If you want to use WCF service provided by ASF, consider starting ASF as administrator, or giving proper permissions!.
        /// </summary>
        internal static string ErrorWCFAddressAccessDeniedException {
            get {
                return ResourceManager.GetString("ErrorWCFAddressAccessDeniedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting....
        /// </summary>
        internal static string Exiting {
            get {
                return ResourceManager.GetString("Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global config file has been changed!.
        /// </summary>
        internal static string GlobalConfigChanged {
            get {
                return ResourceManager.GetString("GlobalConfigChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring trade: {0}.
        /// </summary>
        internal static string IgnoringTrade {
            get {
                return ResourceManager.GetString("IgnoringTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in to {0}....
        /// </summary>
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bots are running, exiting....
        /// </summary>
        internal static string NoBotsAreRunning {
            get {
                return ResourceManager.GetString("NoBotsAreRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing our session!.
        /// </summary>
        internal static string RefreshingOurSession {
            get {
                return ResourceManager.GetString("RefreshingOurSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejecting trade: {0}.
        /// </summary>
        internal static string RejectingTrade {
            get {
                return ResourceManager.GetString("RejectingTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting....
        /// </summary>
        internal static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required version: {0} | Found version: {1}.
        /// </summary>
        internal static string RuntimeVersionComparison {
            get {
                return ResourceManager.GetString("RuntimeVersionComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} runtime version is OK..
        /// </summary>
        internal static string RuntimeVersionOK {
            get {
                return ResourceManager.GetString("RuntimeVersionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code: {0}.
        /// </summary>
        internal static string StatusCode {
            get {
                return ResourceManager.GetString("StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        internal static string TimeSpanDay {
            get {
                return ResourceManager.GetString("TimeSpanDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        internal static string TimeSpanDays {
            get {
                return ResourceManager.GetString("TimeSpanDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        internal static string TimeSpanHour {
            get {
                return ResourceManager.GetString("TimeSpanHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        internal static string TimeSpanHours {
            get {
                return ResourceManager.GetString("TimeSpanHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        internal static string TimeSpanMinute {
            get {
                return ResourceManager.GetString("TimeSpanMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string TimeSpanMinutes {
            get {
                return ResourceManager.GetString("TimeSpanMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 second.
        /// </summary>
        internal static string TimeSpanSecond {
            get {
                return ResourceManager.GetString("TimeSpanSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        internal static string TimeSpanSeconds {
            get {
                return ResourceManager.GetString("TimeSpanSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocking parental account....
        /// </summary>
        internal static string UnlockingParentalAccount {
            get {
                return ResourceManager.GetString("UnlockingParentalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for new version....
        /// </summary>
        internal static string UpdateCheckingNewVersion {
            get {
                return ResourceManager.GetString("UpdateCheckingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading new version... While waiting, consider donating if you appreciate the work being done! :).
        /// </summary>
        internal static string UpdateDownloadingNewVersion {
            get {
                return ResourceManager.GetString("UpdateDownloadingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update process finished!.
        /// </summary>
        internal static string UpdateFinished {
            get {
                return ResourceManager.GetString("UpdateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ASF version is available! Consider updating yourself!.
        /// </summary>
        internal static string UpdateNewVersionAvailable {
            get {
                return ResourceManager.GetString("UpdateNewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local version: {0} | Remote version: {1}.
        /// </summary>
        internal static string UpdateVersionInfo {
            get {
                return ResourceManager.GetString("UpdateVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; Please enter your Device ID (including &quot;android:&quot;): .
        /// </summary>
        internal static string UserInputDeviceID {
            get {
                return ResourceManager.GetString("UserInputDeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; Please enter your 2FA code from your Steam authenticator app: .
        /// </summary>
        internal static string UserInputSteam2FA {
            get {
                return ResourceManager.GetString("UserInputSteam2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; Please enter SteamGuard auth code that was sent on your e-mail: .
        /// </summary>
        internal static string UserInputSteamGuard {
            get {
                return ResourceManager.GetString("UserInputSteamGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; Please enter your Steam login: .
        /// </summary>
        internal static string UserInputSteamLogin {
            get {
                return ResourceManager.GetString("UserInputSteamLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; Please enter Steam parental PIN: .
        /// </summary>
        internal static string UserInputSteamParentalPIN {
            get {
                return ResourceManager.GetString("UserInputSteamParentalPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; Please enter your Steam password: .
        /// </summary>
        internal static string UserInputSteamPassword {
            get {
                return ResourceManager.GetString("UserInputSteamPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; Please enter undocumented value of {1}: .
        /// </summary>
        internal static string UserInputUnknown {
            get {
                return ResourceManager.GetString("UserInputUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt; Please enter your WCF host: .
        /// </summary>
        internal static string UserInputWCFHost {
            get {
                return ResourceManager.GetString("UserInputWCFHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        internal static string WarningFailed {
            get {
                return ResourceManager.GetString("WarningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received unknown confirmation type, please report this: {0}.
        /// </summary>
        internal static string WarningMobileAuthenticatorUnknownConfirmationType {
            get {
                return ResourceManager.GetString("WarningMobileAuthenticatorUnknownConfirmationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASF detected unsupported runtime version, program might NOT run correctly in current environment. You&apos;re running it at your own risk without support!.
        /// </summary>
        internal static string WarningRuntimeUnsupported {
            get {
                return ResourceManager.GetString("WarningRuntimeUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} runtime version is too old!.
        /// </summary>
        internal static string WarningRuntimeVersionTooOld {
            get {
                return ResourceManager.GetString("WarningRuntimeVersionTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing more than {0} games concurrently is not possible, only first {0} entries from {1} will be used!.
        /// </summary>
        internal static string WarningTooManyGamesToPlay {
            get {
                return ResourceManager.GetString("WarningTooManyGamesToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring WCF command because --client wasn&apos;t specified: {0}.
        /// </summary>
        internal static string WarningWCFIgnoringCommand {
            get {
                return ResourceManager.GetString("WarningWCFIgnoringCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answered to WCF command: {0} with: {1}.
        /// </summary>
        internal static string WCFAnswered {
            get {
                return ResourceManager.GetString("WCFAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF server ready!.
        /// </summary>
        internal static string WCFReady {
            get {
                return ResourceManager.GetString("WCFReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF response received: {0}.
        /// </summary>
        internal static string WCFResponseReceived {
            get {
                return ResourceManager.GetString("WCFResponseReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending command: {0} to WCF server on {1}....
        /// </summary>
        internal static string WCFSendingCommand {
            get {
                return ResourceManager.GetString("WCFSendingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting WCF server on {0}....
        /// </summary>
        internal static string WCFStarting {
            get {
                return ResourceManager.GetString("WCFStarting", resourceCulture);
            }
        }
    }
}
