//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiSteamFarm.OfficialPlugins.SteamTokenDumper.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ArchiSteamFarm.OfficialPlugins.SteamTokenDumper.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PluginDisabledMissingBuildToken {
            get {
                return ResourceManager.GetString("PluginDisabledMissingBuildToken", resourceCulture);
            }
        }
        
        internal static string PluginDisabledInConfig {
            get {
                return ResourceManager.GetString("PluginDisabledInConfig", resourceCulture);
            }
        }
        
        internal static string PluginInitializedAndEnabled {
            get {
                return ResourceManager.GetString("PluginInitializedAndEnabled", resourceCulture);
            }
        }
        
        internal static string FileCouldNotBeLoadedFreshInit {
            get {
                return ResourceManager.GetString("FileCouldNotBeLoadedFreshInit", resourceCulture);
            }
        }
        
        internal static string BotNoAppsToRefresh {
            get {
                return ResourceManager.GetString("BotNoAppsToRefresh", resourceCulture);
            }
        }
        
        internal static string BotRetrievingTotalAppAccessTokens {
            get {
                return ResourceManager.GetString("BotRetrievingTotalAppAccessTokens", resourceCulture);
            }
        }
        
        internal static string BotRetrievingAppAccessTokens {
            get {
                return ResourceManager.GetString("BotRetrievingAppAccessTokens", resourceCulture);
            }
        }
        
        internal static string BotFinishedRetrievingAppAccessTokens {
            get {
                return ResourceManager.GetString("BotFinishedRetrievingAppAccessTokens", resourceCulture);
            }
        }
        
        internal static string BotFinishedRetrievingTotalAppAccessTokens {
            get {
                return ResourceManager.GetString("BotFinishedRetrievingTotalAppAccessTokens", resourceCulture);
            }
        }
        
        internal static string BotRetrievingTotalDepots {
            get {
                return ResourceManager.GetString("BotRetrievingTotalDepots", resourceCulture);
            }
        }
        
        internal static string BotRetrievingAppInfos {
            get {
                return ResourceManager.GetString("BotRetrievingAppInfos", resourceCulture);
            }
        }
        
        internal static string BotFinishedRetrievingAppInfos {
            get {
                return ResourceManager.GetString("BotFinishedRetrievingAppInfos", resourceCulture);
            }
        }
        
        internal static string BotFinishedRetrievingDepotKeys {
            get {
                return ResourceManager.GetString("BotFinishedRetrievingDepotKeys", resourceCulture);
            }
        }
        
        internal static string BotFinishedRetrievingTotalDepots {
            get {
                return ResourceManager.GetString("BotFinishedRetrievingTotalDepots", resourceCulture);
            }
        }
        
        internal static string SubmissionNoNewData {
            get {
                return ResourceManager.GetString("SubmissionNoNewData", resourceCulture);
            }
        }
        
        internal static string SubmissionNoContributorSet {
            get {
                return ResourceManager.GetString("SubmissionNoContributorSet", resourceCulture);
            }
        }
        
        internal static string SubmissionInProgress {
            get {
                return ResourceManager.GetString("SubmissionInProgress", resourceCulture);
            }
        }
        
        internal static string SubmissionFailedTooManyRequests {
            get {
                return ResourceManager.GetString("SubmissionFailedTooManyRequests", resourceCulture);
            }
        }
        
        internal static string SubmissionSuccessful {
            get {
                return ResourceManager.GetString("SubmissionSuccessful", resourceCulture);
            }
        }
        
        internal static string SubmissionSuccessfulNewApps {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulNewApps", resourceCulture);
            }
        }
        
        internal static string SubmissionSuccessfulVerifiedApps {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulVerifiedApps", resourceCulture);
            }
        }
        
        internal static string SubmissionSuccessfulNewPackages {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulNewPackages", resourceCulture);
            }
        }
        
        internal static string SubmissionSuccessfulVerifiedPackages {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulVerifiedPackages", resourceCulture);
            }
        }
        
        internal static string SubmissionSuccessfulNewDepots {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulNewDepots", resourceCulture);
            }
        }
        
        internal static string SubmissionSuccessfulVerifiedDepots {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulVerifiedDepots", resourceCulture);
            }
        }
        
        internal static string PluginSecretListInitialized {
            get {
                return ResourceManager.GetString("PluginSecretListInitialized", resourceCulture);
            }
        }
        
        internal static string LoadingGlobalCache {
            get {
                return ResourceManager.GetString("LoadingGlobalCache", resourceCulture);
            }
        }
        
        internal static string ValidatingGlobalCacheIntegrity {
            get {
                return ResourceManager.GetString("ValidatingGlobalCacheIntegrity", resourceCulture);
            }
        }
        
        internal static string GlobalCacheIntegrityValidationFailed {
            get {
                return ResourceManager.GetString("GlobalCacheIntegrityValidationFailed", resourceCulture);
            }
        }
    }
}
