//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiSteamFarm.OfficialPlugins.SteamTokenDumper.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiSteamFarm.OfficialPlugins.SteamTokenDumper.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished retrieving {0} app access tokens..
        /// </summary>
        internal static string BotFinishedRetrievingAppAccessTokens {
            get {
                return ResourceManager.GetString("BotFinishedRetrievingAppAccessTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished retrieving {0} app infos..
        /// </summary>
        internal static string BotFinishedRetrievingAppInfos {
            get {
                return ResourceManager.GetString("BotFinishedRetrievingAppInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished retrieving {0} depot keys..
        /// </summary>
        internal static string BotFinishedRetrievingDepotKeys {
            get {
                return ResourceManager.GetString("BotFinishedRetrievingDepotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished retrieving a total of {0} app access tokens..
        /// </summary>
        internal static string BotFinishedRetrievingTotalAppAccessTokens {
            get {
                return ResourceManager.GetString("BotFinishedRetrievingTotalAppAccessTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished retrieving all depot keys for a total of {0} apps..
        /// </summary>
        internal static string BotFinishedRetrievingTotalDepots {
            get {
                return ResourceManager.GetString("BotFinishedRetrievingTotalDepots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no apps that require a refresh on this bot instance..
        /// </summary>
        internal static string BotNoAppsToRefresh {
            get {
                return ResourceManager.GetString("BotNoAppsToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving {0} app access tokens....
        /// </summary>
        internal static string BotRetrievingAppAccessTokens {
            get {
                return ResourceManager.GetString("BotRetrievingAppAccessTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving {0} app infos....
        /// </summary>
        internal static string BotRetrievingAppInfos {
            get {
                return ResourceManager.GetString("BotRetrievingAppInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving {0} depot keys....
        /// </summary>
        internal static string BotRetrievingDepotKeys {
            get {
                return ResourceManager.GetString("BotRetrievingDepotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving a total of {0} app access tokens....
        /// </summary>
        internal static string BotRetrievingTotalAppAccessTokens {
            get {
                return ResourceManager.GetString("BotRetrievingTotalAppAccessTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving all depots for a total of {0} apps....
        /// </summary>
        internal static string BotRetrievingTotalDepots {
            get {
                return ResourceManager.GetString("BotRetrievingTotalDepots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be loaded, a fresh instance will be initialized....
        /// </summary>
        internal static string FileCouldNotBeLoadedFreshInit {
            get {
                return ResourceManager.GetString("FileCouldNotBeLoadedFreshInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently disabled according to your configuration. If you&apos;d like to help SteamDB in data submission, please check out our wiki..
        /// </summary>
        internal static string PluginDisabledInConfig {
            get {
                return ResourceManager.GetString("PluginDisabledInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been disabled due to a missing build token.
        /// </summary>
        internal static string PluginDisabledMissingBuildToken {
            get {
                return ResourceManager.GetString("PluginDisabledMissingBuildToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been initialized successfully, thank you in advance for your help. The first submission will happen in approximately {1} from now..
        /// </summary>
        internal static string PluginInitializedAndEnabled {
            get {
                return ResourceManager.GetString("PluginInitializedAndEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} initialized, the plugin will not resolve any of those: {1}..
        /// </summary>
        internal static string PluginSecretListInitialized {
            get {
                return ResourceManager.GetString("PluginSecretListInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The submission has failed due to too many requests sent, we&apos;ll try again in approximately {0} from now..
        /// </summary>
        internal static string SubmissionFailedTooManyRequests {
            get {
                return ResourceManager.GetString("SubmissionFailedTooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting a total of registered apps/packages/depots: {0}/{1}/{2}....
        /// </summary>
        internal static string SubmissionInProgress {
            get {
                return ResourceManager.GetString("SubmissionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not submit the data because there is no valid SteamID set that we could classify as a contributor. Consider setting up {0} property..
        /// </summary>
        internal static string SubmissionNoContributorSet {
            get {
                return ResourceManager.GetString("SubmissionNoContributorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no new data to submit, everything is up-to-date..
        /// </summary>
        internal static string SubmissionNoNewData {
            get {
                return ResourceManager.GetString("SubmissionNoNewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been successfully submitted. The server has registered a total of new apps/packages/depots: {0} ({1} verified)/{2} ({3} verified)/{4} ({5} verified)..
        /// </summary>
        internal static string SubmissionSuccessful {
            get {
                return ResourceManager.GetString("SubmissionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New apps: {0}.
        /// </summary>
        internal static string SubmissionSuccessfulNewApps {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulNewApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New depots: {0}.
        /// </summary>
        internal static string SubmissionSuccessfulNewDepots {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulNewDepots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New packages: {0}.
        /// </summary>
        internal static string SubmissionSuccessfulNewPackages {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulNewPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified apps: {0}.
        /// </summary>
        internal static string SubmissionSuccessfulVerifiedApps {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulVerifiedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified depots: {0}.
        /// </summary>
        internal static string SubmissionSuccessfulVerifiedDepots {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulVerifiedDepots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified packages: {0}.
        /// </summary>
        internal static string SubmissionSuccessfulVerifiedPackages {
            get {
                return ResourceManager.GetString("SubmissionSuccessfulVerifiedPackages", resourceCulture);
            }
        }
    }
}
