//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiSteamFarm.OfficialPlugins.ItemsMatcher.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ArchiSteamFarm.OfficialPlugins.ItemsMatcher.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ActivelyMatchingItemsRound {
            get {
                return ResourceManager.GetString("ActivelyMatchingItemsRound", resourceCulture);
            }
        }
        
        internal static string ListingAnnouncing {
            get {
                return ResourceManager.GetString("ListingAnnouncing", resourceCulture);
            }
        }
        
        internal static string MatchingFound {
            get {
                return ResourceManager.GetString("MatchingFound", resourceCulture);
            }
        }
        
        internal static string TradeOfferFailed {
            get {
                return ResourceManager.GetString("TradeOfferFailed", resourceCulture);
            }
        }
        
        internal static string ActivelyMatchingSomeConfirmationsFailed {
            get {
                return ResourceManager.GetString("ActivelyMatchingSomeConfirmationsFailed", resourceCulture);
            }
        }
        
        internal static string PluginDisabledCustomBuild {
            get {
                return ResourceManager.GetString("PluginDisabledCustomBuild", resourceCulture);
            }
        }
    }
}
