name: ASF-crowdin-ci

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions: {}

jobs:
  upload:
    environment: dev-crowdin
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        show-progress: false
        submodules: recursive

    - name: Upload latest strings for translation on Crowdin
      uses: crowdin/github-action@e0c8f73cdc0fafde9396e056c5038217000a32d1 # v2.16.4
      with:
        crowdin_branch_name: main
        config: '.github/crowdin.yml'
        project_id: ${{ secrets.ASF_CROWDIN_PROJECT_ID }}
        token: ${{ secrets.ASF_CROWDIN_API_TOKEN }}
